In [3]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix, f1_score

In [2]:
df = pd.read_csv("train.csv")
df.info()

FileNotFoundError: [Errno 2] No such file or directory: 'train.csv'

In [15]:
df.head(5)

Number words female  Total words  Number of words lead  \
0                 1512         6394                2251.0   
1                 1524         8780                2020.0   
2                  155         4176                 942.0   
3                 1073         9855                3440.0   
4                 1317         7688                3835.0   

   Difference in words lead and co-lead  Number of male actors  Year  \
0                                   343                      2  1995   
1                                  1219                      9  2001   
2                                   787                      7  1968   
3                                  2623                     12  2002   
4                                  3149                      8  1988   

   Number of female actors  Number words male  Gross  Mean Age Male  \
0                        5               2631  142.0      51.500000   
1                        4               5236   37.0      39.125000   
2                        1               3079  376.0      42.500000   
3                        2               5342   19.0      35.222222   
4                        4               2536   40.0      45.250000   

   Mean Age Female  Age Lead  Age Co-Lead    Lead  
0        42.333333      46.0         65.0  Female  
1        29.333333      58.0         34.0    Male  
2        37.000000      46.0         37.0    Male  
3        21.500000      33.0         23.0    Male  
4        45.000000      36.0         39.0    Male

In [16]:
x = df.drop('Lead', axis=1)
y = df['Lead']

In [17]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=42)

In [18]:
BernNB = BernoulliNB(binarize= 0.1)
BernNB.fit(x_train, y_train)
print(BernNB)

y_expect = y_test
y_pred = BernNB.predict(x_test)
print(accuracy_score(y_expect, y_pred))
print(confusion_matrix(y_expect, y_pred))
print("Male: ", f1_score(y_expect, y_pred, average="binary", pos_label="Male"))
print("Female: ", f1_score(y_expect, y_pred, average="binary", pos_label="Female"))

BernoulliNB(binarize=0.1)
0.7384615384615385
[[  4  68]
 [  0 188]]
Male:  0.8468468468468469
Female:  0.10526315789473684


In [19]:
MultiNB = MultinomialNB()
MultiNB.fit(x_train, y_train)
print(MultiNB)
y_pred = MultiNB.predict(x_test)
print(accuracy_score(y_expect, y_pred))
print(confusion_matrix(y_expect, y_pred))
print("Male: ", f1_score(y_expect, y_pred,average="binary", pos_label="Male"))
print("Female: ", f1_score(y_expect, y_pred,average="binary", pos_label="Female"))

MultinomialNB()
0.5961538461538461
[[ 52  20]
 [ 85 103]]
Male:  0.662379421221865
Female:  0.4976076555023922


In [20]:
GausNB = GaussianNB()
GausNB.fit(x_train, y_train)
print(GausNB)
y_pred = GausNB.predict(x_test)
print(accuracy_score(y_expect, y_pred))
print(confusion_matrix(y_expect, y_pred))
print("Male: ", f1_score(y_expect, y_pred, average="binary", pos_label="Male"))
print("Female: ", f1_score(y_expect, y_pred, average="binary", pos_label="Female"))

GaussianNB()
0.7769230769230769
[[ 41  31]
 [ 27 161]]
Male:  0.8473684210526314
Female:  0.5857142857142857
